### ISSUE TITLE
Bug in density file

### ISSUE THREAD

**Issue by sjneph** [Altius/hotspot2#21]
Eric pointed out the following mistake on line 48 of density-peaks.bash:
bedmap --faster --sweep-all --chrom "$chr" --range "$rangepad" --delim "\t" --echo --echo-ref-row-id --count - "$tags"

--count should be changed to --sum for consistency with what we've always done when calculating densities.

**Comment by fwip** [comment]
Fixed by 61d2de9f, will be in 1.1 release.
