### ISSUE TITLE
Drosophila mappable regions

### ISSUE THREAD

**Issue by brianpenghe** [Altius/hotspot2#28]
I was trying to run extractCenterSites.sh to get stated but I need an MAPPABLE-REGIONS file I guess. Do you know how I can generate that file? I know mouse and human files can be downloaded from ENCODE but what about Drosophila?

**Comment by erynes** [comment]
We have Drosophila resource files that we can provide, but they're for genome build dm6. Please e-mail me directly (erynes@altius.org) for further info.
